import styles from './ChartFrame.module.css';

/** Shared chart / analytics layout classes (no domain CSS). */
export const chartChrome = {
  frame: styles.frame,
  frameTall: styles.frameTall,
  plot: styles.plot,
  card: styles.card,
  emptyHint: styles.emptyHint,
  chartToolbar: styles.chartToolbar,
  chartTitle: styles.chartTitle,
  chartLegendRow: styles.chartLegendRow,
  filterCard: styles.filterCard,
  filterBody: styles.filterBody,
  filterGrid: styles.filterGrid,
  filterActions: styles.filterActions,
  filterActionsEnd: styles.filterActionsEnd,
  metricGrid: styles.metricGrid,
  metricCard: styles.metricCard,
  metricLabel: styles.metricLabel,
  metricValue: styles.metricValue,
  metricHint: styles.metricHint,
  comparisonCard: styles.comparisonCard,
  comparisonHeader: styles.comparisonHeader,
  comparisonTitle: styles.comparisonTitle,
  comparisonBody: styles.comparisonBody,
  comparisonTile: styles.comparisonTile,
  comparisonMetricLabel: styles.comparisonMetricLabel,
  comparisonRow: styles.comparisonRow,
  comparisonRowLabel: styles.comparisonRowLabel,
  comparisonRowValue: styles.comparisonRowValue,
  comparisonDelta: styles.comparisonDelta,
  comparisonDeltaUp: styles.comparisonDeltaUp,
  comparisonDeltaDown: styles.comparisonDeltaDown,
  collapsibleCard: styles.collapsibleCard,
  collapsibleTrigger: styles.collapsibleTrigger,
  chevron: styles.chevron,
  chevronOpen: styles.chevronOpen,
  autoGridFill: styles.autoGridFill,
  autoGridFillWide: styles.autoGridFillWide,
} as const;
