/** Plan REST paths. */
export const PLAN_ENDPOINTS = {
  BASE: '/plans',
  BY_ID: (id: string) => `/plans/${id}`,
  SHOP_STATUS: '/plans/shop/status',
  SHOP_SUGGESTED: (shopId: string) => `/plans/shop/${shopId}/suggested`,
  SHOP_ASSIGN: (shopId: string) => `/plans/shop/${shopId}/assign`,
  SHOP_USAGE: '/plans/shop/usage',
  SHOP_TRANSACTIONS: '/plans/shop/transactions',
  SHOP_WALLET: '/plans/shop/wallet',
  REFERRALS_ME: '/referrals/me',
  REFERRAL_REWARDS: '/referrals/rewards',
  PAYMENT_CONFIG: '/plans/payment/config',
  PAYMENT_CHECKOUT: '/plans/payment/checkout',
  PAYMENT_VERIFY: '/plans/payment/verify',
  ORDER_QUOTE: '/plans/orders/quote',
  ADDONS: '/plans/addons',
  VOUCHER_VALIDATE: '/plans/vouchers/validate',
  CAMPAIGN_ACTIVE: '/campaigns/active',
  ADMIN_MIS: '/admin/mis/plans',
  ADMIN_REFERRAL_ATTRIBUTIONS: '/admin/referrals/attributions',
  ADMIN_REFERRAL_ATTRIBUTION_ACTION: (id: string, action: 'approve' | 'reject') =>
    `/admin/referrals/attributions/${id}/${action}`,
  ADMIN_REFERRAL_REWARDS: '/admin/referrals/rewards',
  ADMIN_REFERRAL_REWARD_ACTION: (id: string, action: 'approve' | 'void' | 'clawback') =>
    `/admin/referrals/rewards/${id}/${action}`,
  ADMIN_ADDONS: '/admin/addons',
  ADMIN_VOUCHERS: '/admin/vouchers',
  ADMIN_VOUCHER: (id: string) => `/admin/vouchers/${id}`,
  ADMIN_VOUCHER_ACTIVE: (id: string) => `/admin/vouchers/${id}/active`,
  ADMIN_VOUCHER_REDEMPTIONS: (id: string) => `/admin/vouchers/${id}/redemptions`,
  ADMIN_WALLET: (shopId: string) => `/admin/wallets/${encodeURIComponent(shopId)}`,
  ADMIN_WALLET_ADJUSTMENTS: (shopId: string) =>
    `/admin/wallets/${encodeURIComponent(shopId)}/adjustments`,
} as const;
