/** Plan REST paths. */
export const PLAN_ENDPOINTS = {
  BASE: '/plans',
  BY_ID: (id: string) => `/plans/${id}`,
  SHOP_STATUS: '/plans/shop/status',
  SHOP_SUGGESTED: (shopId: string) => `/plans/shop/${shopId}/suggested`,
  SHOP_ASSIGN: (shopId: string) => `/plans/shop/${shopId}/assign`,
  SHOP_USAGE: '/plans/shop/usage',
  SHOP_TRANSACTIONS: '/plans/shop/transactions',
  SHOP_WALLET: '/plans/shop/wallet',
  REFERRALS_ME: '/referrals/me',
  REFERRAL_REWARDS: '/referrals/rewards',
  PAYMENT_CONFIG: '/plans/payment/config',
  PAYMENT_CHECKOUT: '/plans/payment/checkout',
  PAYMENT_VERIFY: '/plans/payment/verify',
  ORDER_QUOTE: '/plans/orders/quote',
  ADDONS: '/plans/addons',
  VOUCHER_VALIDATE: '/plans/vouchers/validate',
  CAMPAIGN_ACTIVE: '/campaigns/active',
} as const;
