import type { CSSProperties } from 'react';

/** Product registration page chrome — layout only (no CSS modules). */
export const pageStyles = {
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.625rem',
  } satisfies CSSProperties,
  helperText: {
    fontSize: '0.875rem',
    color: 'var(--text-tertiary)',
    marginTop: '0.25rem',
    listStyle: 'none',
    paddingLeft: 0,
  } satisfies CSSProperties,
  separator: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    margin: '20px 0',
    padding: '0 12px',
    position: 'relative',
  } satisfies CSSProperties,
  separatorLine: {
    flex: 1,
    height: 2,
    background:
      'linear-gradient(to right, transparent, var(--border-color, #e2e8f0) 10%, var(--border-color, #e2e8f0) 90%, transparent)',
    position: 'relative',
  } satisfies CSSProperties,
  separatorContent: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 16px',
    background: 'var(--bg-card)',
    border: '2px solid var(--border-color)',
    borderRadius: 20,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  separatorIcon: {
    fontSize: '1.2rem',
  } satisfies CSSProperties,
  separatorText: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
  } satisfies CSSProperties,
  productsSection: {
    marginTop: 0,
    paddingTop: '1.5rem',
    borderTop: '1px solid var(--border-color)',
    scrollMarginTop: 20,
  } satisfies CSSProperties,
  productsHeader: {
    marginBottom: '1.25rem',
  } satisfies CSSProperties,
  reviewBanner: {
    marginBottom: '1.5rem',
  } satisfies CSSProperties,
  reviewBannerContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.25rem',
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.1) 0%, rgba(6, 182, 212, 0.1) 100%)',
    border: '2px solid #3b82f6',
    borderRadius: 12,
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.15)',
  } satisfies CSSProperties,
  reviewBannerIcon: {
    fontSize: '1.5rem',
    flexShrink: 0,
  } satisfies CSSProperties,
  reviewBannerText: {
    flex: 1,
    fontSize: '0.95rem',
    color: 'var(--text-primary)',
    lineHeight: 1.5,
  } satisfies CSSProperties,
  reviewBannerClose: {
    background: 'none',
    border: 'none',
    fontSize: '1.5rem',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: 0,
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  keyboardNavHint: {
    margin: '0.35rem 0 0.75rem',
    fontSize: '0.78rem',
    color: 'var(--text-secondary)',
    lineHeight: 1.45,
  } satisfies CSSProperties,
  keyboardNavHintLabel: {
    fontWeight: 600,
    color: 'var(--text-tertiary)',
  } satisfies CSSProperties,
  kbdInline: {
    fontFamily: 'ui-monospace, monospace',
    fontSize: '0.72em',
    padding: '0.08rem 0.28rem',
    borderRadius: 3,
    border: '1px solid var(--border-color)',
    background: 'var(--bg-secondary)',
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  emptyState: {
    padding: '3rem 2rem',
    textAlign: 'center',
    background: 'var(--bg-primary)',
    border: '2px dashed var(--border-color)',
    borderRadius: 12,
    color: 'var(--text-secondary)',
    marginTop: 0,
  } satisfies CSSProperties,
  schemaLoadingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    padding: '3rem 2rem',
    textAlign: 'center',
    background: 'var(--bg-primary)',
    border: '2px dashed var(--border-color)',
    borderRadius: 12,
    marginTop: 0,
  } satisfies CSSProperties,
} as const;

/** Per-product accordion list view. */
export const accordionStyles = {
  productsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  } satisfies CSSProperties,
  productAccordion: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border-color)',
    borderRadius: 12,
    overflow: 'visible',
    transition: 'all 0.2s',
  } satisfies CSSProperties,
  accordionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.25rem 1.5rem',
    background: 'var(--bg-primary)',
    cursor: 'pointer',
    transition: 'background 0.2s',
    userSelect: 'none',
  } satisfies CSSProperties,
  accordionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    fontSize: '1.1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    flex: 1,
  } satisfies CSSProperties,
  accordionIcon: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    width: '1rem',
    display: 'inline-block',
  } satisfies CSSProperties,
  accordionSubtitle: {
    fontSize: '0.9rem',
    fontWeight: 400,
    color: 'var(--text-secondary)',
    marginLeft: '0.5rem',
  } satisfies CSSProperties,
  removeProductBtn: {
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    color: '#dc2626',
    width: 32,
    height: 32,
    borderRadius: 6,
    fontSize: '1.5rem',
    lineHeight: 1,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  } satisfies CSSProperties,
  accordionContent: {
    padding: '1.5rem',
    borderTop: '1px solid var(--border-color)',
  } satisfies CSSProperties,
  formRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '1rem',
    marginBottom: '1.75rem',
  } satisfies CSSProperties,
  reminderSection: {
    marginTop: '1.5rem',
    paddingTop: '1.5rem',
    borderTop: '1px solid var(--border-color)',
  } satisfies CSSProperties,
  ratesSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginBottom: '1rem',
  } satisfies CSSProperties,
  ratesHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '0.5rem',
  } satisfies CSSProperties,
  addRateBtn: {
    padding: '0.5rem 1rem',
    fontSize: '0.9rem',
    fontWeight: 500,
    background: 'linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%)',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    color: 'white',
  } satisfies CSSProperties,
  rateRow: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
  } satisfies CSSProperties,
  rateNameInput: {
    flex: 1,
    padding: '0.5rem 0.75rem',
    border: '1px solid var(--border-color)',
    borderRadius: 6,
    fontSize: '0.95rem',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  ratePriceInput: {
    width: '6rem',
    padding: '0.5rem 0.75rem',
    border: '1px solid var(--border-color)',
    borderRadius: 6,
    fontSize: '0.95rem',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  removeRateBtn: {
    padding: '0.25rem 0.5rem',
    fontSize: '1.25rem',
    lineHeight: 1,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
  } satisfies CSSProperties,
  unitHint: {
    fontSize: '0.8rem',
    color: 'var(--text-tertiary)',
    lineHeight: 1.35,
  } satisfies CSSProperties,
} as const;

/** Shared vendor search, invoice totals, dropdowns. */
export const vendorStyles = {
  sharedSection: {
    marginBottom: 0,
    padding: '0.9rem 1rem',
    border: '1px solid var(--border-color)',
    borderRadius: 10,
    background:
      'linear-gradient(180deg, color-mix(in srgb, var(--bg-primary) 88%, #ffffff 12%) 0%, var(--bg-primary) 100%)',
  } satisfies CSSProperties,
  sharedTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    marginBottom: '0.65rem',
    paddingBottom: '0.45rem',
    borderBottom: '1px dashed var(--border-color)',
  } satisfies CSSProperties,
  sharedHint: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    fontWeight: 500,
    letterSpacing: '0.01em',
  } satisfies CSSProperties,
  sharedModeSelect: {
    width: 122,
    minWidth: 122,
    padding: '0.32rem 0.55rem',
    fontSize: '0.78rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    borderRadius: 999,
    borderColor: 'color-mix(in srgb, var(--border-color) 70%, #94a3b8 30%)',
    background: 'var(--bg-card)',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.06)',
  } satisfies CSSProperties,
  sharedInfoGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '1rem',
    alignItems: 'start',
  } satisfies CSSProperties,
  sharedInfoGridSpanFull: {
    gridColumn: '1 / -1',
  } satisfies CSSProperties,
  vendorSection: {
    marginTop: '1.5rem',
    paddingTop: '1.5rem',
    borderTop: '1px solid var(--border-color)',
  } satisfies CSSProperties,
  vendorInfo: {
    marginTop: '1.25rem',
  } satisfies CSSProperties,
  vendorCard: {
    padding: '1rem',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: 8,
  } satisfies CSSProperties,
  vendorNotFound: {
    padding: '1rem',
    background: '#fef3c7',
    border: '1px solid #fcd34d',
    borderRadius: 8,
    marginTop: 4,
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    zIndex: 1000,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  } satisfies CSSProperties,
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    background: 'var(--bg-card)',
    border: '1px solid var(--border-color)',
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 200,
    overflowY: 'auto',
    zIndex: 1000,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  } satisfies CSSProperties,
  dropdownItem: {
    padding: '0.75rem 1rem',
    cursor: 'pointer',
    color: 'var(--text-primary)',
    borderBottom: '1px solid var(--border-color)',
    transition: 'background 0.2s',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  } satisfies CSSProperties,
} as const;

/** Invoice upload + QR scan entry layout (dropzone uses ui-kit FileDropzone). */
export const uploadLayoutStyles = {
  uploadSection: {
    marginTop: 0,
    padding: '2rem',
    borderTop: '1px solid var(--border-color)',
    background:
      'linear-gradient(135deg, rgba(59, 130, 246, 0.03) 0%, rgba(6, 182, 212, 0.03) 100%)',
    borderRadius: 12,
    border: '1px solid var(--border-color)',
    marginBottom: 0,
  } satisfies CSSProperties,
  uploadHeader: {
    marginBottom: '1.5rem',
  } satisfies CSSProperties,
  uploadOptionsHeader: {
    marginBottom: '1rem',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid var(--border-color)',
  } satisfies CSSProperties,
  uploadOptionsLabel: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  } satisfies CSSProperties,
  uploadOptionsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    gap: '1.5rem',
    alignItems: 'stretch',
  } satisfies CSSProperties,
  uploadOptionsOr: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '0 8px',
    alignSelf: 'stretch',
  } satisfies CSSProperties,
  uploadOptionsOrLine: {
    width: 1,
    height: 40,
    background:
      'linear-gradient(to bottom, transparent, var(--border-color, #e2e8f0) 20%, var(--border-color, #e2e8f0) 80%, transparent)',
  } satisfies CSSProperties,
  uploadOptionsOrText: {
    fontSize: '0.75rem',
    fontWeight: 700,
    color: 'var(--text-secondary, #718096)',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    padding: '4px 12px',
    background: 'var(--bg-card)',
    border: '1px solid var(--border-color)',
    borderRadius: 12,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  qrUploadBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '1rem',
    border: '2px solid var(--border-color)',
    borderRadius: 12,
    background:
      'linear-gradient(135deg, rgba(59, 130, 246, 0.08) 0%, rgba(6, 182, 212, 0.08) 100%)',
    color: 'var(--text-primary)',
    fontSize: '1rem',
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'left',
    position: 'relative',
    overflow: 'hidden',
    height: '100%',
    minHeight: 110,
  } satisfies CSSProperties,
  qrBtnIcon: {
    fontSize: '2rem',
    flexShrink: 0,
  } satisfies CSSProperties,
  qrBtnContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    flex: 1,
  } satisfies CSSProperties,
  qrBtnTitle: {
    fontWeight: 600,
    fontSize: '1rem',
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  qrBtnSubtitle: {
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
    fontWeight: 400,
  } satisfies CSSProperties,
} as const;
