/** Lucide-based sidebar / command-palette icon keys (kebab-case). */
export const NAV_ICON_NAMES = [
  'layout-dashboard',
  'package',
  'search',
  'wrench',
  'smartphone',
  'undo-2',
  'upload',
  'trending-up',
  'scroll-text',
  'contact',
  'users',
  'truck',
  'store',
  'user',
  'mail',
  'inbox',
  'handshake',
  'megaphone',
  'message-circle',
  'coffee',
  'shopping-cart',
  'clipboard-list',
  'circle-dollar-sign',
  'credit-card',
  'receipt',
  'calendar',
  'triangle-alert',
  'book-open',
  'pencil-line',
  'factory',
  'scale',
  'lock',
  'circle',
] as const;

export type NavIconName = (typeof NAV_ICON_NAMES)[number];
