import axios from 'axios';
import { apiClient } from '@inventory-platform/api-client';
import type { ApiResponse } from '@inventory-platform/contracts';
import { CAFE_ORDER_ENDPOINTS } from './endpoints';
import type { CafeOrder, CafeKot, OpenOrderBody, PunchBody } from '../types/order';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api/v1';

/**
 * Same raw-axios pattern as `punch` above (and
 * core/product/src/api/credit-note.api.ts): replicates the
 * Authorization/X-Shop-Id headers apiClient's interceptor would otherwise
 * add, with a blob response type for a PDF document.
 */
async function fetchPdfBlob(path: string): Promise<Blob> {
  const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
  const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

  const response = await axios.get(`${API_BASE_URL}${path}`, {
    responseType: 'blob',
    headers: {
      Authorization: token ? `Bearer ${token}` : '',
      ...(shopId ? { 'X-Shop-Id': shopId } : {}),
    },
  });

  return response.data;
}

export const cafeOrderApi = {
  listOpen: async (): Promise<CafeOrder[]> => {
    const res = await apiClient.get<ApiResponse<CafeOrder[]>>(CAFE_ORDER_ENDPOINTS.ORDERS);
    return res.data;
  },

  get: async (orderId: string): Promise<CafeOrder> => {
    const res = await apiClient.get<ApiResponse<CafeOrder>>(CAFE_ORDER_ENDPOINTS.ORDER(orderId));
    return res.data;
  },

  open: async (body: OpenOrderBody): Promise<CafeOrder> => {
    const res = await apiClient.post<ApiResponse<CafeOrder>>(CAFE_ORDER_ENDPOINTS.ORDERS, body);
    return res.data;
  },

  /**
   * apiClient.post(endpoint, data) takes no per-call headers argument
   * (see platform/api-client/src/lib/client.ts), so the Idempotency-Key
   * header is attached with the raw-axios pattern used by
   * core/product/src/api/credit-note.api.ts and inventory.api.ts, replicating
   * the Authorization/X-Shop-Id headers apiClient's interceptor would
   * otherwise add. The key is generated by the caller and reused on retry;
   * a fresh key is a fresh punch.
   */
  punch: async (orderId: string, body: PunchBody, idempotencyKey: string): Promise<CafeKot[]> => {
    const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
    const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

    const response = await axios.post<ApiResponse<CafeKot[]>>(
      `${API_BASE_URL}${CAFE_ORDER_ENDPOINTS.PUNCH(orderId)}`,
      body,
      {
        headers: {
          Authorization: token ? `Bearer ${token}` : '',
          ...(shopId ? { 'X-Shop-Id': shopId } : {}),
          'Idempotency-Key': idempotencyKey,
        },
      },
    );

    return response.data.data;
  },

  getKotPdf: async (kotId: string): Promise<Blob> =>
    fetchPdfBlob(CAFE_ORDER_ENDPOINTS.KOT_DOCUMENT(kotId)),
};
