import { apiClient } from '@inventory-platform/api-client';
import type { ApiResponse } from '@inventory-platform/contracts';
import { CAFE_KOT_ENDPOINTS } from './endpoints';
import type { CafeKot } from '../types/kot';

/**
 * Every call here goes through `apiClient`, including the kitchen-facing writes.
 *
 * They used to be issued through raw `axios`, hand-copying the Authorization/X-Shop-Id
 * headers, because `apiClient.post` took no per-call headers and this module needs to send a
 * non-blank `Idempotency-Key`. The cost was the whole response interceptor: a token that
 * expires mid-shift returned a bare `AxiosError`, so the 401 handler never bounced the
 * cashier to login and the dialog showed "Request failed with status code 401" next to a
 * button they could press forever. 402 plan-expired never fired either, and nothing became
 * an `ApiError`. `apiClient` now carries `ApiRequestOptions.headers` and blob-bodied
 * `getBlob`/`postBlob`, so there is no longer a reason to leave this layer.
 */
function idempotent(idempotencyKey: string) {
  return { headers: { 'Idempotency-Key': idempotencyKey } };
}

export const cafeKotApi = {
  /**
   * Punches the pending round for `purchaseId` into kitchen tickets, and resolves with the
   * tickets the server created.
   *
   * The **server** derives the delta from the cart itself — what is on the order minus what
   * the kitchen has already been sent — so this request carries no body at all, only the
   * Idempotency-Key header. A client-computed delta would be a second opinion about what the
   * kitchen has seen, and the only authoritative one lives on the server.
   *
   * The key is generated by the caller once per punch attempt and reused on retry; a fresh
   * key is a fresh punch — see `lib/idempotencyAttempt.ts`'s `keyAfter` for the retention
   * rule, and `lib/punchKeyStore.ts` for why it is parked outside the component.
   */
  punch: async (purchaseId: string, idempotencyKey: string): Promise<CafeKot[]> => {
    const response = await apiClient.post<ApiResponse<CafeKot[]>>(
      CAFE_KOT_ENDPOINTS.PUNCH(purchaseId),
      undefined,
      idempotent(idempotencyKey),
    );
    return response.data;
  },

  /**
   * Reprints an already-issued ticket: no new ticket, `reprintCount` increments, and the
   * returned PDF is stamped REPRINT so a cook cannot read it as a second order. Requires a
   * non-blank Idempotency-Key like every other kitchen-facing write.
   *
   * Reads the response as the slip itself rather than as JSON, and it has to: the stamp lives
   * only on that render. `GET .../document` deliberately never stamps REPRINT, so fetching
   * the PDF in a second call after reprinting would hand a cook an unstamped slip — which
   * reads as a fresh order for food already being made.
   */
  reprint: (kotId: string, idempotencyKey: string): Promise<Blob> =>
    apiClient.postBlob(
      CAFE_KOT_ENDPOINTS.KOT_REPRINT(kotId),
      undefined,
      idempotent(idempotencyKey),
    ),

  getKotPdf: (kotId: string): Promise<Blob> =>
    apiClient.getBlob(CAFE_KOT_ENDPOINTS.KOT_DOCUMENT(kotId)),
};
