import axios from 'axios';
import { apiClient } from '@inventory-platform/api-client';
import type { ApiResponse } from '@inventory-platform/contracts';
import { CAFE_KOT_ENDPOINTS, CAFE_TAB_ENDPOINTS } from './endpoints';
import type { CafeKot } from '../types/kot';
import type { CafeFlushTarget, CafeTab, CafeTabLineInput } from '../types/tab';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api/v1';

/**
 * Replicates the Authorization/X-Shop-Id headers apiClient's interceptor would
 * otherwise add (same raw-axios pattern as `punch`/`flush`/`reprint` below, and
 * core/product/src/api/credit-note.api.ts), with a blob response type for a PDF
 * document.
 */
async function fetchPdfBlob(path: string): Promise<Blob> {
  const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
  const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

  const response = await axios.get(`${API_BASE_URL}${path}`, {
    responseType: 'blob',
    headers: {
      Authorization: token ? `Bearer ${token}` : '',
      ...(shopId ? { 'X-Shop-Id': shopId } : {}),
    },
  });

  return response.data;
}

/**
 * POSTs with a non-blank `Idempotency-Key` header. `apiClient.post(endpoint, data)` takes
 * no per-call headers argument (see platform/api-client/src/lib/client.ts), so every
 * kitchen-facing write that requires this header (`punch`, tab `flush`, KOT `reprint`) goes
 * through raw axios instead, replicating the Authorization/X-Shop-Id headers apiClient's
 * interceptor would otherwise add — the same pattern as `fetchPdfBlob` above and
 * core/product/src/api/credit-note.api.ts / inventory.api.ts.
 */
async function postWithIdempotencyKey<T>(
  path: string,
  idempotencyKey: string,
  data?: unknown,
): Promise<T> {
  const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
  const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

  const response = await axios.post<ApiResponse<T>>(`${API_BASE_URL}${path}`, data, {
    headers: {
      Authorization: token ? `Bearer ${token}` : '',
      ...(shopId ? { 'X-Shop-Id': shopId } : {}),
      'Idempotency-Key': idempotencyKey,
    },
  });

  return response.data.data;
}

export const cafeKotApi = {
  /**
   * Punches the pending round for `purchaseId` into kitchen tickets. The server derives
   * the delta from the cart itself, so this request carries no body — only the
   * Idempotency-Key header.
   *
   * The key is generated by the caller once per punch attempt and reused on retry; a
   * fresh key is a fresh punch — see lib/punchBasket.ts's `keyAfter` for the retention
   * rule.
   */
  punch: (purchaseId: string, idempotencyKey: string): Promise<CafeKot[]> =>
    postWithIdempotencyKey<CafeKot[]>(CAFE_KOT_ENDPOINTS.PUNCH(purchaseId), idempotencyKey),

  /**
   * Reprints an already-issued ticket: no new ticket, the slip stamps REPRINT, and
   * `reprintCount` increments. Requires a non-blank Idempotency-Key like every other
   * kitchen-facing write.
   */
  reprint: (kotId: string, idempotencyKey: string): Promise<CafeKot> =>
    postWithIdempotencyKey<CafeKot>(CAFE_KOT_ENDPOINTS.KOT_REPRINT(kotId), idempotencyKey),

  getKotPdf: async (kotId: string): Promise<Blob> =>
    fetchPdfBlob(CAFE_KOT_ENDPOINTS.KOT_DOCUMENT(kotId)),
};

export const cafeTabApi = {
  /** The cashier's own open tabs — the list endpoint returns only their own. */
  list: async (): Promise<CafeTab[]> => {
    const response = await apiClient.get<ApiResponse<CafeTab[]>>(CAFE_TAB_ENDPOINTS.TABS());
    return response.data;
  },

  open: async (): Promise<CafeTab> => {
    const response = await apiClient.post<ApiResponse<CafeTab>>(CAFE_TAB_ENDPOINTS.TABS());
    return response.data;
  },

  /** Adds a new line, or updates one already on the tab (same `sellableRef`). */
  addLine: async (tabId: string, line: CafeTabLineInput): Promise<CafeTab> => {
    const response = await apiClient.post<ApiResponse<CafeTab>>(
      CAFE_TAB_ENDPOINTS.TAB_LINES(tabId),
      line,
    );
    return response.data;
  },

  removeLine: async (tabId: string, lineRef: string): Promise<CafeTab> => {
    const response = await apiClient.delete<ApiResponse<CafeTab>>(
      CAFE_TAB_ENDPOINTS.TAB_LINE(tabId, lineRef),
    );
    return response.data;
  },

  close: async (tabId: string): Promise<void> => {
    await apiClient.delete<ApiResponse<null>>(CAFE_TAB_ENDPOINTS.TAB(tabId));
  },

  /**
   * Claims the tab's lines, sends one ticket per kitchen station, appends the lines to
   * `target` (or a new bill when `target.purchaseId` is null), and empties the tab —
   * which keeps its token for the next round. Requires a non-blank Idempotency-Key.
   *
   * The caller must park this key outside of a component ref before calling — see
   * lib/punchKeyStore.ts. A key held only in memory dies on remount or reload, and a
   * flush whose response never arrived then leaves the server holding tickets the client
   * can no longer reach.
   */
  flush: (tabId: string, target: CafeFlushTarget, idempotencyKey: string): Promise<CafeKot[]> =>
    postWithIdempotencyKey<CafeKot[]>(CAFE_TAB_ENDPOINTS.TAB_FLUSH(tabId), idempotencyKey, target),
};
