import axios from 'axios';
import type { ApiResponse } from '@inventory-platform/contracts';
import { CAFE_KOT_ENDPOINTS } from './endpoints';
import type { CafeKot } from '../types/kot';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api/v1';

/**
 * Replicates the Authorization/X-Shop-Id headers apiClient's interceptor would
 * otherwise add (same raw-axios pattern as `punch` below, and
 * core/product/src/api/credit-note.api.ts), with a blob response type for a PDF
 * document.
 */
async function fetchPdfBlob(path: string): Promise<Blob> {
  const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
  const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

  const response = await axios.get(`${API_BASE_URL}${path}`, {
    responseType: 'blob',
    headers: {
      Authorization: token ? `Bearer ${token}` : '',
      ...(shopId ? { 'X-Shop-Id': shopId } : {}),
    },
  });

  return response.data;
}

export const cafeKotApi = {
  /**
   * Punches the pending round for `purchaseId` into kitchen tickets. The server derives
   * the delta from the cart itself, so this request carries no body — only the
   * Idempotency-Key header.
   *
   * apiClient.post(endpoint, data) takes no per-call headers argument (see
   * platform/api-client/src/lib/client.ts), so the Idempotency-Key header is attached
   * with the raw-axios pattern used by core/product/src/api/credit-note.api.ts and
   * inventory.api.ts, replicating the Authorization/X-Shop-Id headers apiClient's
   * interceptor would otherwise add. The key is generated by the caller once per punch
   * attempt and reused on retry; a fresh key is a fresh punch — see
   * lib/punchBasket.ts's `keyAfter` for the retention rule.
   */
  punch: async (purchaseId: string, idempotencyKey: string): Promise<CafeKot[]> => {
    const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
    const shopId = typeof window !== 'undefined' ? localStorage.getItem('x_shop_id') : null;

    const response = await axios.post<ApiResponse<CafeKot[]>>(
      `${API_BASE_URL}${CAFE_KOT_ENDPOINTS.PUNCH(purchaseId)}`,
      undefined,
      {
        headers: {
          Authorization: token ? `Bearer ${token}` : '',
          ...(shopId ? { 'X-Shop-Id': shopId } : {}),
          'Idempotency-Key': idempotencyKey,
        },
      },
    );

    return response.data.data;
  },

  getKotPdf: async (kotId: string): Promise<Blob> =>
    fetchPdfBlob(CAFE_KOT_ENDPOINTS.KOT_DOCUMENT(kotId)),
};
